version: '3.8'
services:
  rabbit:
    image: 'rabbitmq:3.10-management-alpine'
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    ports:
      - '45673:15672'
      - '45672:5672'